steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/prod-project-402708/notes-app:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/prod-project-402708/notes-app:$SHORT_SHA']
images:
- us-central1-docker.pkg.dev/prod-project-402708/notes-app:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
